###
GET http://localhost:8080/calculator/plus?num1=4&num2=5
###
GET http://localhost:8080/calculator/minus?num1=40&num2=5
###
GET http://localhost:8080/calculator/multiply?num1=4&num2=5
###
GET http://localhost:8080/calculator/divide?num1=40&num2=0